### PR TITLE
Fix `<pre />` element flowing to the left

### LINKED ISSUE #2: Code blocks are flowing to the left
Hi again,

After installing the theme, I find that code blocks are now flowing all the way to the left, where they don't belong:
image

Any idea why that may be?

### PR DESCRIPTION
**Pull request by MrWillCom**
Fixes #2.

### CODE REVIEW

**Comment by ddmtrius** [comment]
I tried to reinstall the cupertino theme on my computer, but I found that the bug is still there. The code block is still floating on the left. Also I noticed that you have tried to update the style of the tables as told in issue #23 . I've taken a screenshot and submitted it with the source code as attachments. I hope this will be of some help.
sc
[Untitled-2.txt](https://github.com/MrWillCom/hexo-theme-cupertino/files/9257511/Untitled-2.txt)

**Review by ddmtrius — APPROVED** [review]
The problem still seems to exist. I have specified it [here](https://github.com/MrWillCom/hexo-theme-cupertino/pull/25#issuecomment-1204870983).

**Comment by MrWillCom** [comment]
Emmm... Did you switch to branch `2-code-blocks-flowing-left`, if not, try switching to it?

**Comment by ddmtrius** [comment]
Yes, I did it, and everything was fine this time.
Screenshot 2022-08-04 183630

**Comment by MrWillCom** [comment]
Cool! Thank you very much! Now merged.

**Pull request merged**
